keys:
  - &wafu age17wk9httlw504ndxcmkd6dvfyz2a4sjyzpk4rfj6sqcw6xcre7ums0csdre
  - &yoshika age1ft38svumy94e9ksrvjea5lhjesfcrk0xualfs9jkxmcfzw44tqsqes262t

creation_rules:
  - path_regex: hosts/common/sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *wafu
      - *yoshika