keys:
  - &users:
    - &wafu age17wk9httlw504ndxcmkd6dvfyz2a4sjyzpk4rfj6sqcw6xcre7ums0csdre
  - &hosts:
    - &yoshika age1ft38svumy94e9ksrvjea5lhjesfcrk0xualfs9jkxmcfzw44tqsqes262t
    - &raspi age1wuz4uphtcdkym5prw2pfljcpksft96q0ta2am69czq9g7p8y0ptq4e9rf7

creation_rules:
  - path_regex: hosts/common/optional/sops/secrets.ya?ml$
    key_groups:
    - age:
      - *wafu
      - *yoshika

  - path_regex: hosts/common/optional/sops/[^/]+\.ya?ml$
    key_groups:
    - age:
      - *wafu
      - *yoshika
      - *raspi