name: Build Pi Config

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - raspi
        paths:
            - ".github/workflows/ci.yml"
            - "home-manager/**"
            - "nixos/**"
            - "flake.nix"
            - "flake.lock"

jobs:
    build:
        strategy:
          matrix:
            host:
              - raspi
        runs-on: ubuntu-latest
        steps:
            - name: Install cross-compilation deps
              run: |
                sudo apt update
                sudo apt install -q -y \
                  binfmt-support \
                  gcc-aarch64-linux-gnu \
                  qemu-system-aarch64 \
                  qemu-user-static

            - uses: actions/checkout@v3

            - name: Install Nix
              uses: cachix/install-nix-action@v17
              with:
                extra_nix_config: |
                  extra-platforms = aarch64-linux
                  max-jobs = auto
                  system-features = big-parallel kvm

            - name: Install Cachix
              uses: cachix/cachix-action@v10
              with:
                  name: 3waffel
                  authToken: "${{secrets.CACHIX_AUTH_TOKEN}}"

            - name: Set priority flag
              run: nix-env --set-flag priority 0 cachix

            - name: Build NixOS config
              run: |
                nix build -L --no-link --max-jobs 4 .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
