name: Build Config
on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - master
    paths:
      - ".github/workflows/**"
      - "home-manager/**"
      - "hosts/**"
      - "modules/**"
      - "flake.nix"
      - "flake.lock"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        user:
          - wafu
        host:
          - yoshika
          - raspi
          - bern
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: "5120"
          build-mount-path: "/nix"
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Install cross-compilation deps
        run: |
          sudo apt update
          sudo apt install -q -y \
            binfmt-support \
            gcc-aarch64-linux-gnu \
            qemu-system-aarch64 \
            qemu-user-static
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux
            max-jobs = auto
            system-features = big-parallel kvm
      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: 3waffel
          authToken: "${{secrets.CACHIX_AUTH_TOKEN}}"
          skipPush: true
      - name: Build and push home-manager config
        run: |
          nix build --no-link --print-out-paths .#homeConfigurations.${{ matrix.user }}.activationPackage \
          | cachix push 3waffel
      - name: Build and push NixOS config
        run: |
          nix build --no-link --print-out-paths .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
          | cachix push 3waffel
