#ENC[AES256_GCM,data:zw9inUThop83KWK7JJA1lHtbKLeSMsCbldlMjEr2SxhDxk0GxYD246V2IN9jZ0OWHhSyQQiYmZgvJupwihUCrFLKmminH4rHWA==,iv:LEdoK3TRnlemFdLPfKeP3x+dGD2D1UcY9TAA42BdUb8=,tag:ydpYkTdyxodUjOhbuZvfww==,type:comment]
tailscale-authkey: ENC[AES256_GCM,data:Qpb+5NbDDDGvpS1K1MwmNI9ddQpGZT4bZyddsetIrzfzhVXRoWbe+dGoSvSjL/pn9dmmr662qCSO0vc/Om4=,iv:ni8aq9vNw9IRVYDDokpI0XzsOQCCaPJYMb8jXijnMiA=,tag:+RgZ92MpVl9pFPlq/uL6fA==,type:str]
#ENC[AES256_GCM,data:96IQilquopEN86RoKnlu4Oio6tMHvm2hFiQxA4KBvn+iyIKd+rKHWW7a8tcfFHL6T1fcONKSgw==,iv:LeLwXOals9RTtcL4Kuv/mK9slnSGIO+6WZfTgn6j8Ko=,tag:T8Usz73cNLTPcUKVLcNOPw==,type:comment]
ngrok-authtoken: ENC[AES256_GCM,data:LabZ0tgDhSz3M40BzcIAbnPx0p7VrUs58t5F8c/qM/e3Rjdzh5swIZbfrKImKrMGmA==,iv:zPqgdHjGTmeQKK6rdJjBiZEaJ0+P1ODCx/TWkl5R7bw=,tag:kjctPCYVIPn7wD8srxFFbA==,type:str]
#ENC[AES256_GCM,data:AuURHcXbQ6OaKNd0JW5YXXe8pSHoIB2QA0Wg9xTXNxYOJVFbYxPmselCF1EJlU11XY2jzxG0+RSKihbKG0ctZB9RCPQLgLDl4/U5LV1c9+g2ylLe3OUxRAo/cBIoIQ==,iv:I29+Rvn2PCXU4m2T3X44b+3puUZdWds8zmK2e5KTPsg=,tag:qOLMW8pFQLYaPOhji6ue8w==,type:comment]
openvscode-token: ENC[AES256_GCM,data:tctqsD/iphq3LKmcDccMurR1m8t2GwOq5l+HrR2kidoUVdlb,iv:E+fyqiwxaugy44c9xEKIlbAQX3FWCFvIanlaT53/BKk=,tag:vXRKqHxKmGcljrGHI5TnLQ==,type:str]
sops:
    age:
        - recipient: age1ft38svumy94e9ksrvjea5lhjesfcrk0xualfs9jkxmcfzw44tqsqes262t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQndOcWliMlFkdG9lVTV0
            VkpPK0RKckFNbnBoS0pDc0FnRnpaTDhXOEdRCm03U3YyMXlhL1NpR2lieXZzeWJS
            OGtUSzE2M0k3OHBGb0hyVzZIckMyalEKLS0tIG5ENEc0NVVRajFWUjRnRHZMbGdw
            cTlkUExBUDdQcndOQzZVU2hsR0VEMXcKKQgDPV2SBYSweAJo7CU/p4a2bSu7JgG1
            oFQy9Q86KkPzLMGkqB+52zfZPhKBt8dRN5j8rKcit1pA2NsLItVUog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17wk9httlw504ndxcmkd6dvfyz2a4sjyzpk4rfj6sqcw6xcre7ums0csdre
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOHRWMDdBaVRtL3Mrb2Z3
            dFNBRWNQejFJY2prVnJiSldWdXFkRXlOYmdNCjVJSGU5WnNWek1xK3JGZ1ZJTnls
            MmVvS1pVa3hUa1lHNHVOSlZmbFdsRUUKLS0tIDRObWZtZEYvQ1hWc3VQdzhhY1Zr
            MEhuYVlhMW1jYTc4UmZvcjk3NDRTYWsKbCn3FHuA6jkd1MMqFLO0HCiNuCruwXFN
            E/2g82swrtVF52g8R9fMBJ8T/8pj1tTPsZUU8f9ncJexPHfxI2FBwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:20:26Z"
    mac: ENC[AES256_GCM,data:d4GEYbZrOlvWFyZ0pbujdAbGsAeei7ivQP7ZPbIKdI9yhKWXADtJ9I5M4RuwEKd79sjGOzPBeR0jX2FFvHlyc4sD2G6yi3jqMYumgpOx0ZnV/1+SPbJcoCIKIdYRwpLpROzfpRDzIBt8mbyvTvTDeTvTkDQK0+i066QwMe1uiuI=,iv:Iy/76jgYqcTPXw9tFwXrlTXmRTc5uSX+Qe+0RaNgKj8=,tag:dkETNX/v5kB0rHdW6cMCmg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
